config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'
  
  root 'contacts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :job_histories, :class_name => "ContactJobHistory"
  
  
  def self.search(category, search_key)
    
    if search_key.nil? or search_key.empty?
      return Contact.order(:name)
    else
      return Contact.where("#{category} LIKE ?", "%#{search_key}%").order(:name)
    end
    
  end
  
  
end

app/models/contact_job_history.rb
class ContactJobHistory < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    
    @contacts = Contact.search(params[:category], params[:search_key])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_search_form.html.erb
<%= form_tag contacts_index_path, method: "get" do %>
  
  
  <%= select_tag :category, options_for_select( ["name","company", "city", "country"] , params[:category] )   %>
  
  <%= text_field_tag :search_key, params[:search_key]  %>
  
  <%= submit_tag "search", name: nil %>
  
  <span><i>(search with empty string to get the list of all contacts)</i></span>

<% end %>

app/views/contacts/index.html.erb
<div id="search_panel">
  <h2>Search</h2>
  
  <%= render "search_form" %>

</div>

<br>


<div id="display_panel">
  <h2>Contacts (<%= @contacts.length %>)</h2>
  
  <table>
    
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Company</th>
        <th>City</th>
        <th>Country</th>
        <th>Job History</th>
      </tr>
    </thead>
    
    
    
    <tbody>
      
      <% for contact in @contacts %>
      
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.company %></td>
          <td><%= contact.city %></td>
          <td><%= contact.country %></td>
          
          <td> <!--- job history column --->
            <% if !contact.job_histories.nil? and !contact.job_histories.empty? %>
            <span><%= contact.job_histories[0].company %></span>
              
              <% for prev_comp in contact.job_histories[1..-1] %>
                <span>, <%= prev_comp.company %></span>
              <% end %>
            
            <% end %>
          </td> <!--- job history column END --->
          
        </tr>
      
      <% end %>
      
    </tbody>
    
    
  </table>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchContacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>